apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-api-app
spec:
  replicas: 1  # You can increase this for more replicas if needed
  selector:
    matchLabels:
      app: card-api
  template:
    metadata:
      labels:
        app: card-api
    spec:
      containers:
        - name: card-api
          image: imageregistryaderkz.azurecr.io/cards-api:latest  # Replace with your actual Docker image name
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: card-api-config  # Refers to the configmap for environment variables
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      imagePullSecrets:
        - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: card-api-service
spec:
  selector:
    app: card-api
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80
      targetPort: 8000  # Map to the container's 8000 port
  type: LoadBalancer  # Expose the service to the outside world
